name: Simple CI

on: [pull_request]

jobs:
  run-ci:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: git status -s --untracked-files=no
    - run: npm run lint
    - run: make
